on:
  push:
    tags:
      - "*"
  pull_request:
    branches: [main]
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install PlatformIO
        run: python3 -m pip install platformio==6.1.13

      - name: Build firmwares
        run: FIRMWARE_VERSION=${{github.ref_name}} platformio run

      - name: Build spiffs
        run: FIRMWARE_VERSION=${{github.ref_name}} platformio run -t buildfs

      - name: Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/*/firmware.bin
          retention-days: 1
      - name: spiffs
        uses: actions/upload-artifact@v4
        with:
          name: spiffs
          path: .pio/build/*/spiffs.bin
          retention-days: 1
  release:
    name: Release
    # if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build
      - changelog
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for CHANGELOG
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Download artifacts
        uses: actions/download-artifact@v4
      # - name: Display structure of downloaded files
      #   run: ls -R
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "firmware/*/firmware.bin,spiffs/*/spiffs.bin"
          bodyFile: "CHANGELOG.md"
